name: C/C++ CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        git submodule update --init --recursive --depth 1
        mkdir build
        cd build
        cmake -DBUILD_PYTHON_BINDINGS=true -DVKINLINE_BUILD_TESTS=true -DVKINLINE_INCLUDE_PYTESTS=true ..
        cmake --build .

    - name: install
      run: cmake --build . --target install
